# -*- coding: utf-8 -*-
"""normalising_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x0hlloP5PCHGNYuYm4qqTGSMg3DP3Gl7
"""

from google.colab import files
uploaded = files.upload()

!pip install scikit-learn

import pandas as pd

# Load the dataset
df = pd.read_csv('kaggle.csv')

# Copy the data
df_min_max_scaled = df.copy()

# Columns to normalize
columns_to_normalize = ['URLLength', 'NumDigits', 'NumSpecChar', 'RawWordCount', 'HostnameLength', 'PathLength']

# Apply min-max normalization to the specified columns
for column in columns_to_normalize:
    min_val = df_min_max_scaled[column].min()
    max_val = df_min_max_scaled[column].max()
    df_min_max_scaled[column] = (df_min_max_scaled[column] - min_val) / (max_val - min_val)

# View the normalized data
print(df_min_max_scaled)

# Save the modified DataFrame back to CSV
df_min_max_scaled.to_csv('normalised32.csv', index=False)

from google.colab import files

files.download('normalised32.csv')